// Generated by tools/meditations-search/build-screensaver.mjs. Do not edit.
export default [
  {
    "id": "book1-7",
    "label": "1.7",
    "text": "To read attentively—not to be satisfied with “just getting the gist of it.” And not to fall for every smooth talker."
  },
  {
    "id": "book2-1",
    "label": "2.1",
    "text": "We were born to work together like feet, hands, and eyes, like the two rows of teeth, upper and lower. To obstruct each other is unnatural. To feel anger at someone, to turn your back on him: these are obstructions."
  },
  {
    "id": "book2-4",
    "label": "2.4",
    "text": "Remember how long you’ve been putting this off, how many extensions the gods gave you, and you didn’t use them. At some point you have to recognize what world it is that you belong to; what power rules it and from what source you spring; that there is a limit to the time assigned you, and if you don’t use it to free yourself it will be gone and will never return."
  },
  {
    "id": "book2-11",
    "label": "2.11",
    "text": "You could leave life right now. Let that determine what you do and say and think."
  },
  {
    "id": "book3-3",
    "label": "3.3",
    "text": "You boarded, you set sail, you’ve made the passage. Time to disembark."
  },
  {
    "id": "book4-3",
    "label": "4.3",
    "text": "“The world is nothing but change. Our life is only perception.”"
  },
  {
    "id": "book4-7",
    "label": "4.7",
    "text": "Choose not to be harmed—and you won’t feel harmed."
  },
  {
    "id": "book4-17",
    "label": "4.17",
    "text": "Not to live as if you had endless years ahead of you. Death overshadows you. While you’re alive and able—be good."
  },
  {
    "id": "book4-24",
    "label": "4.24",
    "text": "“If you seek tranquillity, do less.” Or (more accurately) do what’s essential—what the logos of a social being requires, and in the requisite way. Which brings a double satisfaction: to do less, better."
  },
  {
    "id": "book4-31",
    "label": "4.31",
    "text": "Love the discipline you know, and let it support you. Entrust everything willingly to the gods, and then make your way through life—no one’s master and no one’s slave."
  },
  {
    "id": "book4-32",
    "label": "4.32",
    "text": "A key point to bear in mind: The value of attentiveness varies in proportion to its object. You’re better off not giving the small things more time than they deserve."
  },
  {
    "id": "book4-42",
    "label": "4.42",
    "text": "There is nothing bad in undergoing change—or good in emerging from it."
  },
  {
    "id": "book4-48",
    "label": "4.48",
    "text": "To pass through this brief life as nature demands. To give it up without complaint."
  },
  {
    "id": "book5-2",
    "label": "5.2",
    "text": "To shrug it all off and wipe it clean—every annoyance and distraction—and reach utter stillness."
  },
  {
    "id": "book5-6",
    "label": "5.6",
    "text": "Some people, when they do someone a favor, are always looking for a chance to call it in. And some aren’t, but they’re still aware of it—still regard it as a debt. But others don’t even do that. They’re like a vine that produces grapes without looking for anything in return."
  },
  {
    "id": "book5-9",
    "label": "5.9",
    "text": "Not to feel exasperated, or defeated, or despondent because your days aren’t packed with wise and moral actions. But to get back up when you fail, to celebrate behaving like a human—however imperfectly—and fully embrace the pursuit that you’ve embarked on."
  },
  {
    "id": "book5-16",
    "label": "5.16",
    "text": "The things you think about determine the quality of your mind. Your soul takes on the color of your thoughts."
  },
  {
    "id": "book5-20",
    "label": "5.20",
    "text": "What stands in the way becomes the way."
  },
  {
    "id": "book5-23",
    "label": "5.23",
    "text": "Keep in mind how fast things pass by and are gone—those that are now, and those to come. Existence flows past us like a river: the “what” is in constant flux, the “why” has a thousand variations. Nothing is stable, not even what’s right here."
  },
  {
    "id": "book6-11",
    "label": "6.11",
    "text": "When jarred, unavoidably, by circumstances, revert at once to yourself, and don’t lose the rhythm more than you can help. You’ll have a better grasp of the harmony if you keep on going back to it."
  },
  {
    "id": "book6-19",
    "label": "6.19",
    "text": "Not to assume it’s impossible because you find it hard. But to recognize that if it’s humanly possible, you can do it too."
  },
  {
    "id": "book6-21",
    "label": "6.21",
    "text": "If anyone can refute me—show me I’m making a mistake or looking at things from the wrong perspective—I’ll gladly change. It’s the truth I’m after, and the truth never harmed anyone. What harms us is to persist in self-deceit and ignorance."
  },
  {
    "id": "book6-30",
    "label": "6.30",
    "text": "Revere the gods; watch over human beings. Our lives are short. The only rewards of our existence here are an unstained character and unselfish acts."
  },
  {
    "id": "book8-16",
    "label": "8.16",
    "text": "Remember that to change your mind and to accept correction are free acts too. The action is yours, based on your own will, your own decision—and your own mind."
  },
  {
    "id": "book8-22",
    "label": "8.22",
    "text": "Stick to what’s in front of you—idea, action, utterance."
  },
  {
    "id": "book8-29",
    "label": "8.29",
    "text": "To erase false perceptions, tell yourself: I have it in me to keep my soul from evil, lust and all confusion. To see things as they are and treat them as they deserve. Don’t overlook this innate ability."
  },
  {
    "id": "book8-32",
    "label": "8.32",
    "text": "You have to assemble your life yourself—action by action. And be satisfied if each one achieves its goal, as far as it can. No one can keep that from happening."
  },
  {
    "id": "book8-35",
    "label": "8.35",
    "text": "Just as nature takes every obstacle, every impediment, and works around it—turns it to its purposes, incorporates it into itself—so, too, a rational being can turn each setback into raw material and use it to achieve its goal."
  },
  {
    "id": "book8-36",
    "label": "8.36",
    "text": "Don’t let your imagination be crushed by life as a whole. Don’t try to picture everything bad that could possibly happen. Stick with the situation at hand, and ask, “Why is this so unbearable? Why can’t I endure it?” You’ll be embarrassed to answer."
  },
  {
    "id": "book8-47",
    "label": "8.47",
    "text": "External things are not the problem. It’s your assessment of them. Which you can erase right now."
  },
  {
    "id": "book8-51",
    "label": "8.51",
    "text": "No carelessness in your actions. No confusion in your words. No imprecision in your thoughts. No retreating into your own soul, or trying to escape it. No overactivity."
  },
  {
    "id": "book9-4",
    "label": "9.4",
    "text": "To do harm is to do yourself harm. To do an injustice is to do yourself an injustice—it degrades you."
  },
  {
    "id": "book9-13",
    "label": "9.13",
    "text": "Today I escaped from anxiety. Or no, I discarded it, because it was within me, in my own perceptions—not outside."
  },
  {
    "id": "book9-29",
    "label": "9.29",
    "text": "Do what nature demands. Get a move on—if you have it in you—and don’t worry whether anyone will give you credit for it. And don’t go expecting Plato’s Republic; be satisfied with even the smallest progress, and treat the outcome of it all as unimportant."
  },
  {
    "id": "book10-4",
    "label": "10.4",
    "text": "If they’ve made a mistake, correct them gently and show them where they went wrong. If you can’t do that, then the blame lies with you. Or no one."
  },
  {
    "id": "book10-16",
    "label": "10.16",
    "text": "To stop talking about what the good man is like, and just be one."
  },
  {
    "id": "book11-9",
    "label": "11.9",
    "text": "As you move forward in the logos, people will stand in your way. They can’t keep you from doing what’s healthy; don’t let them stop you from putting up with them either. Take care on both counts. Not just sound judgments, solid actions—tolerance as well, for those who try to obstruct us or give us trouble in other ways."
  },
  {
    "id": "book11-18",
    "label": "11.18",
    "text": "How much more damage anger and grief do than the things that cause them."
  },
  {
    "id": "book12-4",
    "label": "12.4",
    "text": "It never ceases to amaze me: we all love ourselves more than other people, but care more about their opinion than our own. If a god appeared to us—or a wise human being, even—and prohibited us from concealing our thoughts or imagining anything without immediately shouting it out, we wouldn’t make it through a single day. That’s how much we value other people’s opinions—instead of our own."
  },
  {
    "id": "book12-17",
    "label": "12.17",
    "text": "If it’s not right, don’t do it. If it’s not true, don’t say it."
  },
  {
    "id": "book12-22",
    "label": "12.22",
    "text": "It’s all in how you perceive it. You’re in control. You can dispense with misperception at will, like rounding the point. Serenity, total calm, safe anchorage."
  },
  {
    "id": "book12-36",
    "label": "12.36",
    "text": "So make your exit with grace—the same grace shown to you."
  }
];
